### ISSUE TITLE
How to ignore an element

### ISSUE THREAD

**Issue by seguri** [xmlet/XsdParser#16]
Hello,

Is there a way to ignore an element? I have an XSD that contains a tag I'm not interested in, `<osd:`, and it would be nice to just ignore it. At the moment it is throwing parsing exceptions.

I'm thinking about creating a visitor for each element to ignore, but maybe you have a better solution.

Thanks

**Comment by lcduarte** [comment]
Hello,

Are you sure the exception is due to that element? I've added an element, osd:element, and the parser ignores it, since there isn't any mapper to that element. 

In the current version of this library it only parses types based on the given configuration, if you didn't provide any it shouldn't have any issues with that type of element.

**Comment by seguri** [comment]
Hello Luís,

Have you also declared the namespace for `osd:`?

**Comment by lcduarte** [comment]
No... But what's the point of declaring it if you want to ignore it?

**Comment by seguri** [comment]
I'm receiving an XSD from an external program that generates it...

**Comment by lcduarte** [comment]
Send me the xsd file, I'll see what I can do.
