### ISSUE TITLE
can't parse the node of appinfo inside the annotation

### ISSUE THREAD

**Issue by AhmadDevMaster** [xmlet/XsdParser#17]
in the elements tree always get one empty item inside the app inof list in the annotation node.
is there a way to get the value of it.
<xs:annotation>
			<xs:appinfo>
				<info:MetaType value="Text"/>
				<info:LogicalType value="Text"/>
				<info:FinFormat value="16x"/>
			</xs:appinfo>
		</xs:annotation>

**Comment by lcduarte** [comment]
Hello,

I've changed the way that the AppInfo is parsed in order to return the exact contents of the tag. This should solve your issue. Update to the latest version ([1.0.24](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.24)), and close this issue if it is resolved.

Thanks for using this library, leave a star if it was helpful :)

**Comment by AhmadDevMaster** [comment]
thanks a lot , it's really useful library.
