### ISSUE TITLE
Reference resolving doesn't work if different namespaces are used

### ISSUE THREAD

**Issue by kaijMueller** [xmlet/XsdParser#4]
Hi,
if a element contains a namespace in the type attribute which refers to another schema, then the reference can't be resolved. Please find a sample attached.
xsd_1 uses a type which is defined in xsd_2. This reference can't be resolved.

Code:
`public static void main(final String[] args) {
		final String path = "xsd_1.xml";
		final XsdParser parser = new XsdParser(path);
		System.out.println(parser.getUnsolvedReferences().size());
}`

It would be great if you could make the reference resolving namespace sensitive.

Thank you,
Kai

[XSDTest.zip](https://github.com/xmlet/XsdParser/files/2650267/XSDTest.zip)

**Comment by lcduarte** [comment]
Hello, 

Thank you for the issue. 

The reference solving process was indeed implemented without consideration for different namespaces. I won't implement it right away since it might take some significant changes in the project. Meanwhile to go around it you can use direct references, i.e. instead of using `tw:two` using only `two` on `xsd_1.xml`.

**Comment by kaijMueller** [comment]
Okay, thank you. I already did this :-)

**Comment by kaijMueller** [comment]
Hi,
if you don't plan big features currently, I would be happy to solve this issue via PR.

**Comment by lcduarte** [comment]
Hello, 

Sure, I don't have much time currently so if you want go ahead and thanks in advance :)

**Comment by kaijMueller** [comment]
Hi,
just want to let you know, that I'll drop my current work on this. I forgot, that this does not only include the xsd namespace but also other namespaces. In addition, the xsd prefix for datatypes makes everything horrible complicated. 
I have currently other projects which require a higher attention, so please don't expect further work my side in the next time.

I hope to see maybe a fix for this in future.

**Comment by kaijMueller** [comment]
Hi,
just want to let you more, that it really seems like way to complicated for the time I currently have. Sorry for this. 
Looking forward to see for a fix in the future

**Comment by LouizFC** [comment]
in my use case, I need to resolve many namespaces at same time. I am creating a `XmlnsMap` that will support "alias" keys, I don't know exactly how it can help with this case, but [I commited it to a branch](https://github.com/LouizFC/XsdParser/tree/feature/introduce-xmlns-map), be warned that it is not ready yet.

In my use case I need to implement a `Map` interface, so I am focusing on that first, then I will work on the alias stuff.

The idea of the map is sharing values between namespaces, like so:

```java
List<String> baseList = new ArrayList<>();
baseList.add("one");

XmlnsMap<List<String>> xmlnsMap = new XmlnsMap<>();
xmlnsMap.put("xsd:list", baseList);
xmlnsMap.addAlias("xsd", ""); // need better naming
xmlnsMap.addAlias("xsd", "xs");

List<String> list = xmlnsMap.get("list"); // ["one"]
list.add("two");
List<String> xsList = xmlnsMap.get("xs:list"); // ["one", "two"]
xsList.add("three");
List<String> xsdList = xmlnsMap.get("xsd:list"); // ["one", "two", "three"];

boolean isEqual = xsList == baseList && list == baseList;  // true
```

**Comment by lcduarte** [comment]
Hello,

I've just performed a new release, [1.0.18](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.18). This release introduces multiple namespace usage and reworks how the ``xsd:includes`` works.

``xsd:includes``:

Using this type will result in including all the elements defined in another XSD file in the current context. This means that ``XsdParser`` considers that included files share the same namespace and therefore don't require any prefix while referring elements with the ``ref`` keyword. This also means that included files shouldn't have elements with repeated names.

Multiple namespace usage:

```java
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:el="EL_Namespace"
        xmlns:sp="SP_Namespace">
    <xs:include schemaLocation="./src/test/resources/ns1_part2.xsd"/>
    <xs:import namespace="EL_Namespace" schemaLocation="./src/test/resources/ns2.xsd"/>
    <xs:import namespace="SP_Namespace" schemaLocation="./src/test/resources/ns3.xsd"/>
    <xs:element name="MotherOfBtns">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="BTN"/>
                <xs:element ref="el:BTN"/>
                <xs:element ref="sp:BTN"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
```

In this example we have two distinct approaches, one file is included and two different namespaces are used. The namespaces should have distinct prefixes and the referred namespace should be present in a ``xsd:import`` element. The name of the element used is the same for the purpose of proving that there is no collision of names since the elements are defined in different namespaces. Each referred element has a different attribute with a different name to prove that the reference resolution is correct, the test is [Here](https://github.com/xmlet/XsdParser/blob/master/src/test/java/org/xmlet/xsdparser/NamespaceTest.java) if you want to take a look.

I think this pretty much covers this issue, I'll keep this open to receive any feedback.

PS: XsdParser only supports local files/namespaces. Any namespace referred should be by a path to the local file.

**Comment by kaijMueller** [comment]
Hey,
that's a great piece of work. Let me test this in the next time.

One minor comment from my side. I've seen that you have now a parser configuration which has the namespace map. Maybe it's worth to omit this by just using the java xml style.
So instead of testing of the current node is "xsd:complexType" or whatever the parser config tells you, you could use the localname (complexType) and the XSD namespace. Java will resolve the prefix, so that a search by namespace works find.
`document.getDocumentElement().getElementsByTagNameNS(namespaceURI, localName);
if(node.getLocalName().equals("complexType") && node.getNamespaceURI().equals("..."))`

Please note, that you need to configure the document builder factory to be namespace sensitive.

I know that this will get more complicated when it comes to attributes, because normally the string content doesn't has a namespace but in XSD it has (e.g. xsd:string). So you would need to store the current prefix somewhere (can variant from file to file) and resolve accordantly.

Best regards,
Kai
