### ISSUE TITLE
Attributes in simpleContext

### ISSUE THREAD

**Issue by skfcz** [xmlet/XsdParser#49]
**Describe the bug**
I parse the unitsML schema, containing a type like

```
<xsd:complexType name="NameType">
		<xsd:annotation>
			<xsd:documentation>Type for name.  Used for names in units, quantities, and prefixes.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:token">
				<xsd:attribute ref="xml:lang"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
```

I then try to get the attribute using 
```
 final XsdExtension xsdExtension = simpleContent.getXsdExtension();
xsdExtension.getXsdAttributes(). xsdAttributes.forEach(xsdAttribute -> { ... };
```
But get no attribute

**Expected behavior**

Get the attributes nested on the xsd extension

**Additional context**
The schema is found here https://schema.unitsml.org/docs/unitsmllite/unitsmllite-v0.9.18/

PS: Is there something like a user group for xmlet?

**Comment by lcduarte** [comment]
Hello, 

First thanks for using the library!

It looks like the library won't return the attribute because it is an Unsolved Reference to xml:lang. To get around that you would have to import a schema with the xml namespace elements. I've made a small example in this commit:

[Example for Issue 49](https://github.com/xmlet/XsdParser/commit/3f5edefdc86c5a7bd393ccf89b8fe0e77d9cc1b0)

Hope it helps.

Regarding the user group, I don't think so.

Best Regards

**Comment by skfcz** [comment]
Hello Luís, 

thanks very much!

Bye, Carsten
