### ISSUE TITLE
Null Pointer Exception Parsing OCX Schema

### ISSUE THREAD

**Issue by skfcz** [xmlet/XsdParser#50]
**Describe the bug**
When parsing the OCX Schema, one gets a null pointer exception.

**Expected behavior**
No Null Pointer Exception

**Library Version**
[3f5edef](https://github.com/xmlet/XsdParser/commit/3f5edefdc86c5a7bd393ccf89b8fe0e77d9cc1b0)

**Additional context**

On https://github.com/skfcz/XsdParser you find
* one test case with data
* a fix 

and  additional code to access the XsdAttributes default value

**Comment by lcduarte** [comment]
Hello, 

Thanks for using the library, I've been a little busy. 

I've released a new version, [1.2.5](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.5), with a fallback that uses your approach when the Schema is null, because in some cases what you've written is not necessarily true, but your suggestion works in more cases that it did previously so it's always an improvement.

Thanks for your input :)
