### ISSUE TITLE
Attributes are ignored

### ISSUE THREAD

**Issue by skfcz** [xmlet/XsdParser#66]
**Describe the bug**

In the following schema, I do not get the refType attribute
on SeamRef_T

''
	<xs:complexType name="ReferenceBase_T" abstract="true">
		<xs:annotation>
			<xs:documentation>Type definition</xs:documentation>
		</xs:annotation>
		
		<xs:attribute name="name" use="required">
			<xs:annotation>
				<xs:documentation>Custom property name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType> 
<xs:complexType name="BoundedRef_T" abstract="true">
		<xs:annotation>
			<xs:documentation>Type description</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ocx:ReferenceBase_T">

			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SeamRef_T">
		<xs:annotation>
			<xs:documentation>Type definition</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ocx:BoundedRef_T">
				<xs:attribute ref="ocx:refType" use="required" fixed="ocx:Seam"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

''

**Expected behavior**

I expect to get the attribute in e.g. the following code

xsdComplexType.getAllXsdAttributes().forEach(xsdAttribute -> LOG.info("getAllXsdAttributes found {}", xsdAttribute.getName()));

**Additional context**
Full xsd on https://3docx.org/fileadmin/ocx_schema/V300rc7/OCX_Schema.xsd

**Comment by lcduarte** [comment]
Hello,

The method getAllXsdAttributes only returns two kinds of attributes:
* XsdAttributes that are direct children of the XsdComplexType;
* XsdAttributes that are in XsdAttributeGroups that are direct children of the XsdComplexType.

Since the refType attribute is a child of the XsdExtension it isn't returned when invoking the method on the XsdComplexType object.

Sample code to obtain the attribute using your full xsd:

![imagem](https://github.com/xmlet/XsdParser/assets/5586583/84d7ae44-0fea-4e1d-ac2a-7fc6eb6a198f)
