### ISSUE TITLE
XsdParser::getSchemaNode fails with comments

### ISSUE THREAD

**Issue by skfcz** [xmlet/XsdParser#7]
Hello, 

currently XsdParser uses doc.getFirstChild(); to get the XSD root.
This fails terribly with all kinds of schema which have a comment or text node.

My proposal is to use

return doc.getDocumentElement();

Bye, Carsten

**Comment by lcduarte** [comment]
Hi, 

Thanks for the note. I'll introduce that fix with the next release once another feature is requested. I've taken that approach since the XSD documentation states that the xsd:schema should always be the first node of a XSD document, but in any case I'll introduce that fix to prevent any bugs with files that contain comments before the xsd:schema node.

Thank you again.

Regards, 
Luís

**Comment by skfcz** [comment]
Hello Luis, 

good to know. I was a bit desparate, as all schema checking tools
accepted the XML file whereas my tool based on the XsdParser terribly
failed :-)

Bye, Carsten


Am Dienstag, den 21.05.2019, 05:38 -0700 schrieb Luís Duarte:

**Comment by lcduarte** [comment]
Hello,

In [1.0.17](https://github.com/xmlet/XsdParser/tree/xsdParser-1.0.17) this issue is resolved.

I'll close this issue, open another if you get any other problem.

Regards, 
Luís
