### ISSUE TITLE
Inf. lookup with unqualified union memberTypes and circular includes

### ISSUE THREAD

**Issue by jonherrmann** [xmlet/XsdParser#70]
**Describe the bug**
Union memberType names that are not fully qualified lead to an [infinite type lookup](https://github.com/xmlet/XsdParser/blob/master/src/main/java/org/xmlet/xsdparser/core/XsdParserCore.java#L160-L170) if the schema file contains a circular include.

**Expected behavior**
Parser should handle circular includes.

**Library Version**
1.2.14

**Additional context**
```
<!-- a.xsd -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
        xmlns:test="..." 
        targetNamespace="..."
>
    <include schemaLocation="b.xsd"/>

    <simpleType name="TestUnionA1">
        <union memberTypes="time"/>
    </simpleType>

</schema>

<!-- b.xsd -->
<schema>
    <include schemaLocation="a.xsd"/>
</schema>
```

**Comment by lcduarte** [comment]
Hello,

Thanks for using the library and for the issue/fix! I've just made an adjustment to the first if because as it was it never entered in the if even when it should. I've added some extra code to the test you've provided to validate a situation where the if code runs.

I've released a new version [1.2.15](https://github.com/xmlet/XsdParser/tree/xsdParser-1.2.15) with the changes, if you have any issues let me know.
